---

- include: nut.yml

- include: nut-cgi.yml

- name: check if munin-node is installed
  command: dpkg -L munin-node
  register: dpkg_munin_node_check
  ignore_errors: yes

- name: configure munin plugin
  include: munin-plugin.yml
  when: dpkg_munin_node_check.rc == 0
