---

- name: patch nutups_
  command: sed -i 's/upsc $UPS |/upsc $UPS 2> \/dev\/null |/' /usr/share/munin/plugins/nutups_
  become: yes

- name: enable nut plugins
  file:
    src: /usr/share/munin/plugins/nutups_
    dest: /etc/munin/plugins/nutups_ups_{{ item }}
    state: link
  with_items:
    - voltages
    - charge
    - freq
    - current
  become: yes
  notify: nut_restart_munin_node
