---

- name: install packages
  apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - nut-cgi
    - fcgiwrap
  become: yes

- name: add hosts.conf
  template:
    src: hosts.conf
    dest: /etc/nut/hosts.conf
    mode: 0644
  become: yes
