---

- name: install nut
  apt:
    name: nut
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: add udev rules
  template:
    src: nut-ups.rules.sh
    dest: /etc/udev/rules.d/90-nut-ups.rules
    mode: 0644
  become: yes

- name: add configs
  template:
    src: "{{ item }}"
    dest: /etc/nut/{{ item }}
    mode: 0640
    owner: root
    group: nut
  with_items:
    - ups.conf
    - nut.conf
    - upsd.conf
    - upsd.users
  become: yes
  notify:
    - restart_nut_driver
    - restart_nut_monitor

- name: add monitor to upsmon.conf
  blockinfile:
    path: /etc/nut/upsmon.conf
    block: |
      MONITOR ups@localhost 1 upsmon {{ nut_upsmon_password }} master
  become: yes
